apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZGt6dnJzZ2Y2
  CLOUDINARY_KEY: NDI5ODU4MjgyOTE3MjIy
  CLOUDINARY_SECRET: VkFPelVqdTRPdVRSR041NHNfUjJKR1BWWWlB
  MAPBOX_TOKEN: cGsuZXlKMUlqb2laMmxrZFhSMWNtbHphWFpoYzJGcElpd2lZU0k2SW1OdGNUbHJaRzF6YXpBeE1uUXljbTlsWkhOblp6SjVZVFlpZlEuNkRhQW41cmY0NlNGNUpGeTBXVFVmdw==
  DB_URL: bW9uZ29kYitzcnY6Ly9zaXZhc2FpX2RiX3VzZXI6U2l2YUAxOTk5QGNsdXN0ZXIwLmNyZWN3NXEubW9uZ29kYi5uZXQvP2FwcE5hbWU9Q2x1c3RlcjA=
